### ISSUE TITLE
undefined reference to `strlen' collect2: error: ld returned 1 exit status make: *** [Makefile:10: build] Error 1

### ISSUE THREAD

**Issue by mohammednuredin** [pygrum/gimmick#1]
Hi,
How to fix?

─$ make build
x86_64-w64-mingw32-gcc -s -Os -nostdlib -fno-asynchronous-unwind-tables example/main.c *.c -o gimmick.exe -DDEBUG
/usr/bin/x86_64-w64-mingw32-ld: /tmp/ccfPxfso.o:gimmick.c:(.text+0x3d): undefined reference to `strlen'
collect2: error: ld returned 1 exit status
make: *** [Makefile:10: build] Error 1

**Comment by pygrum** [comment]
Should be fixed by https://github.com/pygrum/gimmick/commit/d05a6b1026dbb636757a8245b087c59e40e40720
